language: cpp
compiler:
  - gcc
services:
  - docker
env:
  - TARGET_PLATFORM=mac
  - TARGET_PLATFORM=win
  - TARGET_PLATFORM=lin
before_install:
  - chmod a+rwx src/
  - (cd docker; make .image)
script:
  - (cd docker; make $TARGET_PLATFORM)
