#!/bin/bash
#
# How to run
# cd Xsaitekpanels repo
# ./build-XP12-Xbtn2cmd_win_mac_lin_WithCmake_OnLinux

rm -r Xbtn2cmd/win_x64/*
rm -r Xbtn2cmd/lin_x64/*
rm -r Xbtn2cmd/mac_x64/*


# Windows build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-mingw-w64-x86-64.cmake
cmake --build ./build -v
cp ./build/win.xpl ./Xbtn2cmd/win_x64/Xbtn2cmd.xpl


# Linux build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build ./build -v
cp ./build/lin.xpl ./Xbtn2cmd/lin_x64/Xbtn2cmd.xpl


# Mac build

rm -r build/*
cmake -S ./src -B ./build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=../src/Toolchain-ubuntu-osxcross-11.3.cmake
cmake --build ./build -v
cp ./build/mac.xpl ./Xbtn2cmd/mac_x64/Xbtn2cmd.xpl


cp docs/Xbtn2cmd.pdf Xbtn2cmd/Documentation/Xbtn2cmd.pdf

exec $SHELL
#

