#!/bin/bash
#
# How to run
# ./xp12_xbtn2cmd_plugin_builder/xbtn2cmd/build-XP12-Xbtn2cmd_win_WithDocker_mac_lin_WithCmake_OnLinux

cd xp12_xbtn2cmd_plugin_builder/xbtn2cmd &&
mkdir -p release/Xbtn2cmd/64 &&
mkdir -p release/Xbtn2cmd/mac_x64 &&
mkdir -p release/Xbtn2cmd/mac_arm&&

rm -r src/build-win/*

rm -r Xbtn2cmd/64/*
rm -r Xbtn2cmd/mac_x64/*
rm -r Xbtn2cmd/mac_arm/*

# Have to make Windows build with Docker Ubuntu 18.04
# Because it will not build correctly with Cmake on Ubuntu 20.04
(cd docker; make)

cd src
mkdir -p build
rm -r build/*
cd build
cmake ..
make VERBOSE=1
cd /home/bill/xp12_xbtn2cmd_plugin_builder/xbtn2cmd
cp src/build/lin.xpl release/Xbtn2cmd/64/

cd src
rm -r build/*
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/xp12_xbtn2cmd_plugin_builder/xbtn2cmd/src/Toolchain-ubuntu-osxcross-11.3-x86_64.cmake ..
make VERBOSE=1
cd /home/bill/xp12_xbtn2cmd_plugin_builder/xbtn2cmd
cp src/build/mac.xpl release/Xbtn2cmd/mac_x64/

# cd src
# rm -r build/*
# cd build
# cmake -DCMAKE_TOOLCHAIN_FILE=~/xp12_xbtn2cmd_plugin_builder/xbtn2cmd/src/Toolchain-ubuntu-osxcross-11.3-arm_64.cmake ..
# make VERBOSE=1
# cd /home/bill/xp12_xbtn2cmd_plugin_builder/xbtn2cmd
# cp src/build/mac.xpl release/Xbtn2cmd/mac_arm/

# lipo -create -output Xbtn2cmd/mac_x64/Xbtn2cmd.xpl release/Xbtn2cmd/mac_x64/Xbtn2cmd.xpl release/Xbtn2cmd/mac_arm/Xbtn2cmd.xpl

cp src/build-win/win.xpl Xbtn2cmd/64/
cp release/Xbtn2cmd/64/lin.xpl Xbtn2cmd/64/
cp release/Xbtn2cmd/mac_x64/mac.xpl Xbtn2cmd/64/

cp docs/Xbtn2cmd.pdf Xbtn2cmd/Documentation/Xbtn2cmd.pdf

exec $SHELL
#

