#!/bin/bash
#
# How to run
# ./xp11_xbtn2cmd_plugin_builder/xbtn2cmd/buildXbtn2cmd_lin_win_mac_OnLinux
 
cd xp11_xbtn2cmd_plugin_builder/xbtn2cmd &&
mkdir -p release/Xbtn2cmd/lin_x64 &&
mkdir -p release/Xbtn2cmd/win_x64 &&
mkdir -p release/Xbtn2cmd/mac_x64 &&

cd src
rm -r build/*
cd build
cmake ..
make VERBOSE=1
cd /home/bill/xp11_xbtn2cmd_plugin_builder/xbtn2cmd
cp src/build/Xbtn2cmd.xpl release/Xbtn2cmd/lin_x64/

cd src
rm -r build/*
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/xp11_xbtn2cmd_plugin_builder/xbtn2cmd/src/Toolchain-mingw-w64-x86-64.cmake ..
make VERBOSE=1
cd /home/bill/xp11_xbtn2cmd_plugin_builder/xbtn2cmd
cp src/build/Xbtn2cmd.xpl release/Xbtn2cmd/win_x64/

cd src
rm -r build/*
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/xp11_xbtn2cmd_plugin_builder/xbtn2cmd/src/Toolchain-ubuntu-osxcross-10.11.cmake ..
make VERBOSE=1
cd /home/bill/xp11_xbtn2cmd_plugin_builder/xbtn2cmd
cp src/build/Xbtn2cmd.xpl release/Xbtn2cmd/mac_x64/

cp release/Xbtn2cmd/lin_x64/Xbtn2cmd.xpl Xbtn2cmd/lin_x64/Xbtn2cmd.xpl
cp release/Xbtn2cmd/win_x64/Xbtn2cmd.xpl Xbtn2cmd/win_x64/Xbtn2cmd.xpl
cp release/Xbtn2cmd/mac_x64/Xbtn2cmd.xpl Xbtn2cmd/mac_x64/Xbtn2cmd.xpl

cp docs/Xbtn2cmd.pdf Xbtn2cmd/Documentation/Xbtn2cmd.pdf

exec $SHELL
#

