#!/bin/bash
#
make distclean >/dev/null
rm -rf release
mkdir -p release/Xbtn2cmd/lin_x64 &&
mkdir -p release/Xbtn2cmd/win_x64 &&


qmake -spec linux-g++-4.8-64 Xbtn2cmd_lin_x64.pro && make &&
cp plugin_lin_x64/liblin.xpl.so release/Xbtn2cmd/lin_x64/Xbtn2cmd.xpl
if [ $? != 0 ] ; then
  exit
fi

make distclean >/dev/null
qmake -spec win32-g++ Xbtn2cmd_win_x64.pro && qmake -set CROSS_COMPILE x86_64-w64-mingw32- && make &&
cp plugin_win_x64/release/win.xpl1.dll release/Xbtn2cmd/win_x64/Xbtn2cmd.xpl
if [ $? != 0 ] ; then
  exit
fi


make distclean >/dev/null

#

