name: CMake

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  release:
    type: [created, edited]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2

    - name: "Windows: Configure environment"
      if: runner.os == 'Windows'
      shell: bash
      run: |
        # Select MinGW toolchain instead of the default MSVC.
        echo "CMAKE_GENERATOR=MinGW Makefiles" >> $GITHUB_ENV

    - name: "Linux: Install dependency libraries"
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends freeglut3-dev libudev-dev libopenal-dev

    - name: Configure CMake
      working-directory: ${{github.workspace}}/src
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/src
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: ${{github.workspace}}/build/*.xpl
        if-no-files-found: error

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: binaries
          path: Xbtn2cmd/64

      - uses: actions/upload-artifact@v2
        with:
          name: Xbtn2cmd_plugin
          path: |
            ${{github.workspace}}/Xbtn2cmd*
          if-no-files-found: error

      - name: Create plugin archive
        if: github.event_name == 'release'
        run: zip -r Xbtn2cmd.zip Xbtn2cmd/

      - name: Upload binaries to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Xbtn2cmd.zip
          tag: ${{ github.ref }}
          overwrite: true
